apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/nexora-ecommerce
    targetRevision: HEAD
    path: infrastructure/helm/nexora-service
    helm:
      values: |
        image:
          repository: ghcr.io/nexora/payment-service
          tag: latest
        service:
          port: 3005
        env:
          PORT: "3005"
          KAFKA_BROKERS: "kafka.nexora-infra.svc.cluster.local:9092"
        secrets:
          DATABASE_URL: "postgresql://postgres:postgres@postgres.nexora-infra.svc.cluster.local:5432/nexora_payments"
          STRIPE_SECRET_KEY: "sk_test_..."
  destination:
    server: https://kubernetes.default.svc
    namespace: nexora-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
