events {
  worker_connections 256;
}

http {
  # Upstream services
  upstream api_gateway {
    server host.docker.internal:4000;
  }

  upstream storefront {
    server host.docker.internal:3000;
  }

  server {
    listen 80;
    server_name localhost;

    # API Gateway (REST + GraphQL)
    location /api/ {
      proxy_pass http://api_gateway/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # WebSocket
    location /socket.io/ {
      proxy_pass http://api_gateway;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    # Storefront
    location / {
      proxy_pass http://storefront;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
